version: '3'

services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    ports:
      - '8080:8080'
      - '9901:9901'
    networks:
      - server-net
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    expose:
      # envoy talks to server via this port inside the server-net network.
      - '9090'
    networks:
      - server-net

networks:
  server-net: